services:
  database:
    container_name: tldw-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: tldw
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: dbadmin
    ports:
      - "5432:5432"
    volumes:
      - tldw_volume:/var/lib/postgresql/data

volumes:
  tldw_volume: