services:
  database:
    container_name: local-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: tldw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: