// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=./mock/handler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestMapper is a mock of RequestMapper interface.
type MockRequestMapper[In any] struct {
	ctrl     *gomock.Controller
	recorder *MockRequestMapperMockRecorder[In]
}

// MockRequestMapperMockRecorder is the mock recorder for MockRequestMapper.
type MockRequestMapperMockRecorder[In any] struct {
	mock *MockRequestMapper[In]
}

// NewMockRequestMapper creates a new mock instance.
func NewMockRequestMapper[In any](ctrl *gomock.Controller) *MockRequestMapper[In] {
	mock := &MockRequestMapper[In]{ctrl: ctrl}
	mock.recorder = &MockRequestMapperMockRecorder[In]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestMapper[In]) EXPECT() *MockRequestMapperMockRecorder[In] {
	return m.recorder
}

// Map mocks base method.
func (m *MockRequestMapper[In]) Map(arg0 *http.Request) (In, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Map", arg0)
	ret0, _ := ret[0].(In)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Map indicates an expected call of Map.
func (mr *MockRequestMapperMockRecorder[In]) Map(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockRequestMapper[In])(nil).Map), arg0)
}

// MockResponseMapper is a mock of ResponseMapper interface.
type MockResponseMapper[Out any] struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMapperMockRecorder[Out]
}

// MockResponseMapperMockRecorder is the mock recorder for MockResponseMapper.
type MockResponseMapperMockRecorder[Out any] struct {
	mock *MockResponseMapper[Out]
}

// NewMockResponseMapper creates a new mock instance.
func NewMockResponseMapper[Out any](ctrl *gomock.Controller) *MockResponseMapper[Out] {
	mock := &MockResponseMapper[Out]{ctrl: ctrl}
	mock.recorder = &MockResponseMapperMockRecorder[Out]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseMapper[Out]) EXPECT() *MockResponseMapperMockRecorder[Out] {
	return m.recorder
}

// Map mocks base method.
func (m *MockResponseMapper[Out]) Map(arg0 http.ResponseWriter, arg1 Out) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Map", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Map indicates an expected call of Map.
func (mr *MockResponseMapperMockRecorder[Out]) Map(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockResponseMapper[Out])(nil).Map), arg0, arg1)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// StructCtx mocks base method.
func (m *MockValidator) StructCtx(ctx context.Context, s any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructCtx", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// StructCtx indicates an expected call of StructCtx.
func (mr *MockValidatorMockRecorder) StructCtx(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructCtx", reflect.TypeOf((*MockValidator)(nil).StructCtx), ctx, s)
}
